training_pipeline_config:
  pipeline_name: credit
  artifact_dir: credit_artifact


data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/k17hawk/credit-risk-prediction/main/Data/credit_risk_dataset.csv
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 


data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  loan_to_income_ratio: loan_to_income_ratio
  loan_to_emp_length_ratio: loan_to_emp_length_ratio
  int_rate_to_loan_amt_ratio: int_rate_to_loan_amt_ratio
  income_group: income_group
  age_group: age_group
  loan_amount_group: loan_amount_group
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml

model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models_scikit