random_search:
  class: RandomizedSearchCV
  module: sklearn.model_selection  
  params:
    cv: 5
    n_iter: 10
    verbose: 2
    
model_selection:
  model_0:
    module: sklearn.ensemble
    class: RandomForestClassifier
    params: 
      n_estimators: 10
      criterion: gini
      
    search_param_grid:
      criterion:
          - gini  
          - entropy
          
 